version: '3'
services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: babujaan@1234
      MYSQL_DATABASE: web_db
    ports:
      - "3306:3306"

  app:
    build: .
    ports:
      - "8501:8501"
    depends_on:
      - db
